/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:Speed_PTD[MAX_PLAYERS][15];

//Textdraws

//Player Textdraws
Speed_PTD[playerid][0] = CreatePlayerTextDraw(playerid, 545.000000, 359.000000, "_");
PlayerTextDrawFont(playerid, Speed_PTD[playerid][0], 1);
PlayerTextDrawLetterSize(playerid, Speed_PTD[playerid][0], 0.625000, 5.199983);
PlayerTextDrawTextSize(playerid, Speed_PTD[playerid][0], 310.500000, 119.000000);
PlayerTextDrawSetOutline(playerid, Speed_PTD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, Speed_PTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, Speed_PTD[playerid][0], 2);
PlayerTextDrawColor(playerid, Speed_PTD[playerid][0], -1);
PlayerTextDrawBackgroundColor(playerid, Speed_PTD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, Speed_PTD[playerid][0], -764862721);
PlayerTextDrawUseBox(playerid, Speed_PTD[playerid][0], 1);
PlayerTextDrawSetProportional(playerid, Speed_PTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, Speed_PTD[playerid][0], 0);

Speed_PTD[playerid][1] = CreatePlayerTextDraw(playerid, 447.000000, 343.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, Speed_PTD[playerid][1], 4);
PlayerTextDrawLetterSize(playerid, Speed_PTD[playerid][1], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, Speed_PTD[playerid][1], 70.000000, 78.500000);
PlayerTextDrawSetOutline(playerid, Speed_PTD[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, Speed_PTD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, Speed_PTD[playerid][1], 1);
PlayerTextDrawColor(playerid, Speed_PTD[playerid][1], -764862721);
PlayerTextDrawBackgroundColor(playerid, Speed_PTD[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, Speed_PTD[playerid][1], -764862926);
PlayerTextDrawUseBox(playerid, Speed_PTD[playerid][1], 1);
PlayerTextDrawSetProportional(playerid, Speed_PTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, Speed_PTD[playerid][1], 0);

Speed_PTD[playerid][2] = CreatePlayerTextDraw(playerid, 571.000000, 343.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, Speed_PTD[playerid][2], 4);
PlayerTextDrawLetterSize(playerid, Speed_PTD[playerid][2], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, Speed_PTD[playerid][2], 70.000000, 78.500000);
PlayerTextDrawSetOutline(playerid, Speed_PTD[playerid][2], 1);
PlayerTextDrawSetShadow(playerid, Speed_PTD[playerid][2], 0);
PlayerTextDrawAlignment(playerid, Speed_PTD[playerid][2], 1);
PlayerTextDrawColor(playerid, Speed_PTD[playerid][2], -764862721);
PlayerTextDrawBackgroundColor(playerid, Speed_PTD[playerid][2], 255);
PlayerTextDrawBoxColor(playerid, Speed_PTD[playerid][2], -764862926);
PlayerTextDrawUseBox(playerid, Speed_PTD[playerid][2], 1);
PlayerTextDrawSetProportional(playerid, Speed_PTD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, Speed_PTD[playerid][2], 0);

Speed_PTD[playerid][3] = CreatePlayerTextDraw(playerid, 507.000000, 390.000000, "ENGINE");
PlayerTextDrawFont(playerid, Speed_PTD[playerid][3], 1);
PlayerTextDrawLetterSize(playerid, Speed_PTD[playerid][3], 0.224997, 1.000000);
PlayerTextDrawTextSize(playerid, Speed_PTD[playerid][3], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, Speed_PTD[playerid][3], 0);
PlayerTextDrawSetShadow(playerid, Speed_PTD[playerid][3], 0);
PlayerTextDrawAlignment(playerid, Speed_PTD[playerid][3], 2);
PlayerTextDrawColor(playerid, Speed_PTD[playerid][3], -1);
PlayerTextDrawBackgroundColor(playerid, Speed_PTD[playerid][3], 255);
PlayerTextDrawBoxColor(playerid, Speed_PTD[playerid][3], 50);
PlayerTextDrawUseBox(playerid, Speed_PTD[playerid][3], 0);
PlayerTextDrawSetProportional(playerid, Speed_PTD[playerid][3], 1);
PlayerTextDrawSetSelectable(playerid, Speed_PTD[playerid][3], 0);

Speed_PTD[playerid][4] = CreatePlayerTextDraw(playerid, 584.000000, 390.000000, "LIGHT");
PlayerTextDrawFont(playerid, Speed_PTD[playerid][4], 1);
PlayerTextDrawLetterSize(playerid, Speed_PTD[playerid][4], 0.224997, 1.000000);
PlayerTextDrawTextSize(playerid, Speed_PTD[playerid][4], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, Speed_PTD[playerid][4], 0);
PlayerTextDrawSetShadow(playerid, Speed_PTD[playerid][4], 0);
PlayerTextDrawAlignment(playerid, Speed_PTD[playerid][4], 2);
PlayerTextDrawColor(playerid, Speed_PTD[playerid][4], -1);
PlayerTextDrawBackgroundColor(playerid, Speed_PTD[playerid][4], 255);
PlayerTextDrawBoxColor(playerid, Speed_PTD[playerid][4], 50);
PlayerTextDrawUseBox(playerid, Speed_PTD[playerid][4], 0);
PlayerTextDrawSetProportional(playerid, Speed_PTD[playerid][4], 1);
PlayerTextDrawSetSelectable(playerid, Speed_PTD[playerid][4], 0);

Speed_PTD[playerid][5] = CreatePlayerTextDraw(playerid, 547.000000, 390.000000, "LOCK");
PlayerTextDrawFont(playerid, Speed_PTD[playerid][5], 1);
PlayerTextDrawLetterSize(playerid, Speed_PTD[playerid][5], 0.224997, 1.000000);
PlayerTextDrawTextSize(playerid, Speed_PTD[playerid][5], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, Speed_PTD[playerid][5], 0);
PlayerTextDrawSetShadow(playerid, Speed_PTD[playerid][5], 0);
PlayerTextDrawAlignment(playerid, Speed_PTD[playerid][5], 2);
PlayerTextDrawColor(playerid, Speed_PTD[playerid][5], -1);
PlayerTextDrawBackgroundColor(playerid, Speed_PTD[playerid][5], 255);
PlayerTextDrawBoxColor(playerid, Speed_PTD[playerid][5], 50);
PlayerTextDrawUseBox(playerid, Speed_PTD[playerid][5], 0);
PlayerTextDrawSetProportional(playerid, Speed_PTD[playerid][5], 1);
PlayerTextDrawSetSelectable(playerid, Speed_PTD[playerid][5], 0);

Speed_PTD[playerid][6] = CreatePlayerTextDraw(playerid, 545.000000, 359.000000, "500");
PlayerTextDrawFont(playerid, Speed_PTD[playerid][6], 1);
PlayerTextDrawLetterSize(playerid, Speed_PTD[playerid][6], 0.683330, 2.949998);
PlayerTextDrawTextSize(playerid, Speed_PTD[playerid][6], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, Speed_PTD[playerid][6], 1);
PlayerTextDrawSetShadow(playerid, Speed_PTD[playerid][6], 0);
PlayerTextDrawAlignment(playerid, Speed_PTD[playerid][6], 2);
PlayerTextDrawColor(playerid, Speed_PTD[playerid][6], -1);
PlayerTextDrawBackgroundColor(playerid, Speed_PTD[playerid][6], 255);
PlayerTextDrawBoxColor(playerid, Speed_PTD[playerid][6], 50);
PlayerTextDrawUseBox(playerid, Speed_PTD[playerid][6], 0);
PlayerTextDrawSetProportional(playerid, Speed_PTD[playerid][6], 1);
PlayerTextDrawSetSelectable(playerid, Speed_PTD[playerid][6], 0);

Speed_PTD[playerid][7] = CreatePlayerTextDraw(playerid, 603.000000, 315.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, Speed_PTD[playerid][7], 4);
PlayerTextDrawLetterSize(playerid, Speed_PTD[playerid][7], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, Speed_PTD[playerid][7], 40.000000, 48.500000);
PlayerTextDrawSetOutline(playerid, Speed_PTD[playerid][7], 1);
PlayerTextDrawSetShadow(playerid, Speed_PTD[playerid][7], 0);
PlayerTextDrawAlignment(playerid, Speed_PTD[playerid][7], 1);
PlayerTextDrawColor(playerid, Speed_PTD[playerid][7], -764862721);
PlayerTextDrawBackgroundColor(playerid, Speed_PTD[playerid][7], 255);
PlayerTextDrawBoxColor(playerid, Speed_PTD[playerid][7], -764862926);
PlayerTextDrawUseBox(playerid, Speed_PTD[playerid][7], 1);
PlayerTextDrawSetProportional(playerid, Speed_PTD[playerid][7], 1);
PlayerTextDrawSetSelectable(playerid, Speed_PTD[playerid][7], 0);

Speed_PTD[playerid][8] = CreatePlayerTextDraw(playerid, 623.000000, 328.000000, "FUEL");
PlayerTextDrawFont(playerid, Speed_PTD[playerid][8], 1);
PlayerTextDrawLetterSize(playerid, Speed_PTD[playerid][8], 0.224997, 1.000000);
PlayerTextDrawTextSize(playerid, Speed_PTD[playerid][8], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, Speed_PTD[playerid][8], 0);
PlayerTextDrawSetShadow(playerid, Speed_PTD[playerid][8], 0);
PlayerTextDrawAlignment(playerid, Speed_PTD[playerid][8], 2);
PlayerTextDrawColor(playerid, Speed_PTD[playerid][8], -1);
PlayerTextDrawBackgroundColor(playerid, Speed_PTD[playerid][8], 255);
PlayerTextDrawBoxColor(playerid, Speed_PTD[playerid][8], 50);
PlayerTextDrawUseBox(playerid, Speed_PTD[playerid][8], 0);
PlayerTextDrawSetProportional(playerid, Speed_PTD[playerid][8], 1);
PlayerTextDrawSetSelectable(playerid, Speed_PTD[playerid][8], 0);

Speed_PTD[playerid][9] = CreatePlayerTextDraw(playerid, 623.000000, 338.000000, "100");
PlayerTextDrawFont(playerid, Speed_PTD[playerid][9], 1);
PlayerTextDrawLetterSize(playerid, Speed_PTD[playerid][9], 0.224997, 1.000000);
PlayerTextDrawTextSize(playerid, Speed_PTD[playerid][9], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, Speed_PTD[playerid][9], 0);
PlayerTextDrawSetShadow(playerid, Speed_PTD[playerid][9], 0);
PlayerTextDrawAlignment(playerid, Speed_PTD[playerid][9], 2);
PlayerTextDrawColor(playerid, Speed_PTD[playerid][9], 852308735);
PlayerTextDrawBackgroundColor(playerid, Speed_PTD[playerid][9], 255);
PlayerTextDrawBoxColor(playerid, Speed_PTD[playerid][9], 50);
PlayerTextDrawUseBox(playerid, Speed_PTD[playerid][9], 0);
PlayerTextDrawSetProportional(playerid, Speed_PTD[playerid][9], 1);
PlayerTextDrawSetSelectable(playerid, Speed_PTD[playerid][9], 0);

Speed_PTD[playerid][10] = CreatePlayerTextDraw(playerid, 435.000000, 394.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, Speed_PTD[playerid][10], 4);
PlayerTextDrawLetterSize(playerid, Speed_PTD[playerid][10], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, Speed_PTD[playerid][10], 40.000000, 48.500000);
PlayerTextDrawSetOutline(playerid, Speed_PTD[playerid][10], 1);
PlayerTextDrawSetShadow(playerid, Speed_PTD[playerid][10], 0);
PlayerTextDrawAlignment(playerid, Speed_PTD[playerid][10], 1);
PlayerTextDrawColor(playerid, Speed_PTD[playerid][10], -764862721);
PlayerTextDrawBackgroundColor(playerid, Speed_PTD[playerid][10], 255);
PlayerTextDrawBoxColor(playerid, Speed_PTD[playerid][10], -764862926);
PlayerTextDrawUseBox(playerid, Speed_PTD[playerid][10], 1);
PlayerTextDrawSetProportional(playerid, Speed_PTD[playerid][10], 1);
PlayerTextDrawSetSelectable(playerid, Speed_PTD[playerid][10], 0);

Speed_PTD[playerid][11] = CreatePlayerTextDraw(playerid, 454.000000, 415.000000, "1000");
PlayerTextDrawFont(playerid, Speed_PTD[playerid][11], 1);
PlayerTextDrawLetterSize(playerid, Speed_PTD[playerid][11], 0.224997, 1.000000);
PlayerTextDrawTextSize(playerid, Speed_PTD[playerid][11], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, Speed_PTD[playerid][11], 0);
PlayerTextDrawSetShadow(playerid, Speed_PTD[playerid][11], 0);
PlayerTextDrawAlignment(playerid, Speed_PTD[playerid][11], 2);
PlayerTextDrawColor(playerid, Speed_PTD[playerid][11], 852308735);
PlayerTextDrawBackgroundColor(playerid, Speed_PTD[playerid][11], 255);
PlayerTextDrawBoxColor(playerid, Speed_PTD[playerid][11], 50);
PlayerTextDrawUseBox(playerid, Speed_PTD[playerid][11], 0);
PlayerTextDrawSetProportional(playerid, Speed_PTD[playerid][11], 1);
PlayerTextDrawSetSelectable(playerid, Speed_PTD[playerid][11], 0);

Speed_PTD[playerid][12] = CreatePlayerTextDraw(playerid, 461.000000, 367.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, Speed_PTD[playerid][12], 4);
PlayerTextDrawLetterSize(playerid, Speed_PTD[playerid][12], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, Speed_PTD[playerid][12], 31.000000, 29.000000);
PlayerTextDrawSetOutline(playerid, Speed_PTD[playerid][12], 1);
PlayerTextDrawSetShadow(playerid, Speed_PTD[playerid][12], 0);
PlayerTextDrawAlignment(playerid, Speed_PTD[playerid][12], 2);
PlayerTextDrawColor(playerid, Speed_PTD[playerid][12], -149);
PlayerTextDrawBackgroundColor(playerid, Speed_PTD[playerid][12], 255);
PlayerTextDrawBoxColor(playerid, Speed_PTD[playerid][12], 50);
PlayerTextDrawUseBox(playerid, Speed_PTD[playerid][12], 0);
PlayerTextDrawSetProportional(playerid, Speed_PTD[playerid][12], 1);
PlayerTextDrawSetSelectable(playerid, Speed_PTD[playerid][12], 0);

Speed_PTD[playerid][13] = CreatePlayerTextDraw(playerid, 597.000000, 367.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, Speed_PTD[playerid][13], 4);
PlayerTextDrawLetterSize(playerid, Speed_PTD[playerid][13], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, Speed_PTD[playerid][13], 31.000000, 29.000000);
PlayerTextDrawSetOutline(playerid, Speed_PTD[playerid][13], 1);
PlayerTextDrawSetShadow(playerid, Speed_PTD[playerid][13], 0);
PlayerTextDrawAlignment(playerid, Speed_PTD[playerid][13], 2);
PlayerTextDrawColor(playerid, Speed_PTD[playerid][13], -149);
PlayerTextDrawBackgroundColor(playerid, Speed_PTD[playerid][13], 255);
PlayerTextDrawBoxColor(playerid, Speed_PTD[playerid][13], 50);
PlayerTextDrawUseBox(playerid, Speed_PTD[playerid][13], 0);
PlayerTextDrawSetProportional(playerid, Speed_PTD[playerid][13], 1);
PlayerTextDrawSetSelectable(playerid, Speed_PTD[playerid][13], 0);

Speed_PTD[playerid][14] = CreatePlayerTextDraw(playerid, 450.000000, 407.000000, "HUD:radar_truck");
PlayerTextDrawFont(playerid, Speed_PTD[playerid][14], 4);
PlayerTextDrawLetterSize(playerid, Speed_PTD[playerid][14], 0.224997, 1.000000);
PlayerTextDrawTextSize(playerid, Speed_PTD[playerid][14], 9.000000, 10.000000);
PlayerTextDrawSetOutline(playerid, Speed_PTD[playerid][14], 0);
PlayerTextDrawSetShadow(playerid, Speed_PTD[playerid][14], 0);
PlayerTextDrawAlignment(playerid, Speed_PTD[playerid][14], 2);
PlayerTextDrawColor(playerid, Speed_PTD[playerid][14], -1);
PlayerTextDrawBackgroundColor(playerid, Speed_PTD[playerid][14], 255);
PlayerTextDrawBoxColor(playerid, Speed_PTD[playerid][14], 50);
PlayerTextDrawUseBox(playerid, Speed_PTD[playerid][14], 0);
PlayerTextDrawSetProportional(playerid, Speed_PTD[playerid][14], 1);
PlayerTextDrawSetSelectable(playerid, Speed_PTD[playerid][14], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
